package dev.tevv.taverntales.data

import dev.tevv.taverntales.model.Library
import dev.tevv.taverntales.model.LightFlash
import dev.tevv.taverntales.model.LightSetup
import dev.tevv.taverntales.model.LightSlot
import dev.tevv.taverntales.model.Scene
import dev.tevv.taverntales.model.SceneCollection
import dev.tevv.taverntales.model.SoundEvent
import dev.tevv.taverntales.model.SoundLayer

/**
 * Content shipped with the app. Sounds live in `assets/sounds/` and backgrounds in
 * `res/drawable-nodpi/bg_<key>.webp`; both are generated by the scripts in `tools/`.
 * IDs are stable so built-in content can be recognised later.
 */
object DefaultLibrary {
    const val COLLECTION_ID = "default"

    /** The second built-in collection, added in library format v6. */
    const val ADVENTURES_ID = "default-adventures"

    fun create(): Library = Library(collections = listOf(collection(), adventures()), events = events())

    fun asset(name: String) = "asset:///sounds/$name.ogg"

    /** Lighting for each built-in scene, keyed like the scene ids (`default-<key>`). */
    val lighting: Map<String, LightSetup> = mapOf(
        // Dusk: deep blue sky, violet, and warm lit windows.
        "town" to LightSetup(listOf(LightSlot("#2B3A8C"), LightSlot("#FFB054"), LightSlot("#6A3D9A")), brightness = 0.45f, motion = 0.25f),
        // Fireside: amber and orange with candle and fire flicker.
        "tavern" to LightSetup(
            listOf(LightSlot("#FF8A2B", "candle"), LightSlot("#FFB060"), LightSlot("#FF5A14", "fire")),
            brightness = 0.55f,
            motion = 0.45f,
        ),
        // Torchlight against cold gloom.
        "dungeon" to LightSetup(listOf(LightSlot("#FF7A20", "fire"), LightSlot("#1E2A6A"), LightSlot("#3A2A5A")), brightness = 0.3f, motion = 0.4f),
        // Bright afternoon sun and sky.
        "market" to LightSetup(listOf(LightSlot("#FFE2A8"), LightSlot("#FFC86A"), LightSlot("#8FCBFF")), brightness = 0.9f, motion = 0.15f),
        // Green canopy with sun breaking through.
        "forest" to LightSetup(listOf(LightSlot("#2FA44A"), LightSlot("#FFE7A0"), LightSlot("#86D660")), brightness = 0.6f, motion = 0.35f),
        // Dark blue with glowing crystals.
        "cave" to LightSetup(listOf(LightSlot("#14306E"), LightSlot("#2FD8FF"), LightSlot("#7A3AFF")), brightness = 0.3f, motion = 0.3f),
        // Night at sea: deep water, moonlit teal and a swinging lantern.
        "ship" to LightSetup(listOf(LightSlot("#14306E"), LightSlot("#2FA0C0"), LightSlot("#FFB054", "candle")), brightness = 0.4f, motion = 0.55f),
        // Murky green with sickly marsh light and violet mist.
        "swamp" to LightSetup(listOf(LightSlot("#2E5A24"), LightSlot("#9AC850"), LightSlot("#5A3A7A")), brightness = 0.3f, motion = 0.3f),
        // Torch-lit stone hall with red banners.
        "castle" to LightSetup(listOf(LightSlot("#FFC27A"), LightSlot("#FF8A2B", "fire"), LightSlot("#C0141E")), brightness = 0.6f, motion = 0.3f),
        // Candlelight and gold, with a touch of violet.
        "temple" to LightSetup(listOf(LightSlot("#FFE3B8", "candle"), LightSlot("#FFB054"), LightSlot("#8A5AE0")), brightness = 0.45f, motion = 0.2f),
        // Cold white and ice blue, gusting.
        "blizzard" to LightSetup(listOf(LightSlot("#DDE8FF"), LightSlot("#8FCBFF"), LightSlot("#F0F4FF")), brightness = 0.7f, motion = 0.55f),
    )

    fun collection() = SceneCollection(
        id = COLLECTION_ID,
        name = "Essentials",
        scenes = listOf(
            scene(
                "town", "Town",
                Layer("Town crowd", "town_crowd", 0.7f),
                Layer("Wind", "wind", 0.4f),
                Layer("Horse carts", "horse_cart", 0.5f),
                Layer("Rain", "rain", 0.6f, autoPlay = false),
                Layer("Church bell", "church_bell", 0.7f, autoPlay = false, loop = false),
            ),
            scene(
                "tavern", "Tavern",
                Layer("Tavern music", "tavern_music", 0.55f),
                Layer("Tavern chatter", "tavern_chatter", 0.7f),
                Layer("Hearth fire", "hearth_fire", 0.6f),
                Layer("Rain outside", "rain", 0.35f, autoPlay = false),
            ),
            scene(
                "dungeon", "Dungeon",
                Layer("Dark drone", "dark_drone", 0.6f),
                Layer("Water drips", "water_drips", 0.7f),
                Layer("Torches", "torches", 0.5f),
                Layer("Chains", "chains", 0.5f),
            ),
            scene(
                "market", "Market",
                Layer("Market crowd", "market_crowd", 0.75f),
                Layer("Horse carts", "horse_cart", 0.45f),
                Layer("Street musician", "tavern_music", 0.35f, autoPlay = false),
                Layer("Wind", "wind", 0.3f, autoPlay = false),
            ),
            scene(
                "forest", "Forest",
                Layer("Birdsong", "birdsong", 0.7f),
                Layer("Forest breeze", "forest_breeze", 0.5f),
                Layer("Stream", "stream", 0.45f),
                Layer("Crickets (night)", "crickets", 0.6f, autoPlay = false),
                Layer("Rain", "rain", 0.5f, autoPlay = false),
            ),
            scene(
                "cave", "Cave",
                Layer("Cave wind", "cave_wind", 0.6f),
                Layer("Water drips", "water_drips", 0.7f),
                Layer("Deep drone", "dark_drone", 0.4f),
                Layer("Underground stream", "stream", 0.35f, autoPlay = false),
            ),
        ),
    )

    fun adventures() = SceneCollection(
        id = ADVENTURES_ID,
        name = "Adventures",
        scenes = listOf(
            scene(
                "ship", "Ship at sea",
                Layer("Waves", "ocean_waves", 0.7f),
                Layer("Creaking timbers", "ship_creak", 0.55f),
                Layer("Wind in the sails", "wind", 0.45f),
                Layer("Seagulls", "seagulls", 0.4f, autoPlay = false),
                Layer("Storm rain", "rain", 0.6f, autoPlay = false),
            ),
            scene(
                "swamp", "Swamp",
                Layer("Frogs", "swamp_frogs", 0.7f),
                Layer("Bubbling mud", "mud_bubbles", 0.5f),
                Layer("Insects", "crickets", 0.35f),
                Layer("Dripping water", "water_drips", 0.3f, autoPlay = false),
                Layer("Rain", "rain", 0.5f, autoPlay = false),
            ),
            scene(
                "castle", "Castle hall",
                Layer("Great hall", "great_hall", 0.65f),
                Layer("Hearth fire", "hearth_fire", 0.5f),
                Layer("Minstrels", "tavern_music", 0.35f, autoPlay = false),
                Layer("Wind outside", "wind", 0.3f, autoPlay = false),
            ),
            scene(
                "temple", "Temple",
                Layer("Chanting", "temple_choir", 0.55f),
                Layer("Temple bell", "temple_bells", 0.6f),
                Layer("Candles", "torches", 0.3f),
                Layer("Mountain wind", "wind", 0.3f, autoPlay = false),
            ),
            scene(
                "blizzard", "Blizzard",
                Layer("Blizzard", "blizzard", 0.75f),
                Layer("Howling wind", "wind", 0.4f),
                Layer("Wolves", "wolves", 0.6f, autoPlay = false),
                Layer("Campfire", "hearth_fire", 0.45f, autoPlay = false),
            ),
        ),
    )

    fun events() = listOf(
        SoundEvent("event-fire", "Fireball", asset("event_fire"), icon = "fire", color = "ember", flash = flashes["event-fire"]),
        SoundEvent("event-explosion", "Explosion", asset("event_explosion"), icon = "explosion", color = "crimson", flash = flashes["event-explosion"]),
        SoundEvent("event-light", "Holy light", asset("event_light"), icon = "light", color = "gold", flash = flashes["event-light"]),
        SoundEvent("event-thunder", "Thunder", asset("event_thunder"), icon = "thunder", color = "azure", flash = flashes["event-thunder"]),
        SoundEvent("event-sword", "Sword clash", asset("event_sword"), icon = "sword", color = "steel", flash = flashes["event-sword"]),
        SoundEvent("event-magic", "Arcane spell", asset("event_magic"), icon = "magic", color = "violet", flash = flashes["event-magic"]),
        SoundEvent("event-roar", "Monster roar", asset("event_roar"), icon = "beast", color = "emerald", flash = flashes["event-roar"]),
        SoundEvent("event-arrows", "Arrow volley", asset("event_arrows"), icon = "arrow", color = "umber"),
    )

    /** Light flashes of the built-in events, by event id. */
    val flashes: Map<String, LightFlash> = mapOf(
        "event-fire" to LightFlash(LightFlash.FLASH, "#FF6A14"),
        "event-explosion" to LightFlash(LightFlash.FLASH, "#FFB46A"),
        "event-light" to LightFlash(LightFlash.GLOW, "#FFE08A"),
        "event-thunder" to LightFlash(LightFlash.STROBE, "#DDE8FF"),
        "event-sword" to LightFlash(LightFlash.FLASH, "#E6EEFF"),
        "event-magic" to LightFlash(LightFlash.GLOW, "#9B5CFF"),
        "event-roar" to LightFlash(LightFlash.GLOW, "#C0141E"),
    )

    private class Layer(
        val name: String,
        val sound: String,
        val volume: Float,
        val autoPlay: Boolean = true,
        val loop: Boolean = true,
    )

    private fun scene(key: String, name: String, vararg layers: Layer) = Scene(
        id = "default-$key",
        name = name,
        background = "builtin:$key",
        lighting = lighting[key],
        layers = layers.map {
            SoundLayer(
                id = "default-$key-${it.sound}",
                name = it.name,
                uri = asset(it.sound),
                volume = it.volume,
                autoPlay = it.autoPlay,
                loop = it.loop,
            )
        },
    )
}
