package dev.tevv.taverntales.data

import dev.tevv.taverntales.model.Library
import dev.tevv.taverntales.model.Scene
import dev.tevv.taverntales.model.SceneCollection
import dev.tevv.taverntales.model.SoundEvent
import dev.tevv.taverntales.model.SoundLayer

/**
 * Content shipped with the app. Sounds live in `assets/sounds/` and backgrounds in
 * `res/drawable-nodpi/bg_<key>.webp`; both are generated by the scripts in `tools/`.
 * IDs are stable so built-in content can be recognised later.
 */
object DefaultLibrary {
    const val COLLECTION_ID = "default"

    fun create(): Library = Library(collections = listOf(collection()), events = events())

    fun asset(name: String) = "asset:///sounds/$name.ogg"

    fun collection() = SceneCollection(
        id = COLLECTION_ID,
        name = "Essentials",
        scenes = listOf(
            scene(
                "town", "Town",
                Layer("Town crowd", "town_crowd", 0.7f),
                Layer("Wind", "wind", 0.4f),
                Layer("Horse carts", "horse_cart", 0.5f),
                Layer("Rain", "rain", 0.6f, autoPlay = false),
                Layer("Church bell", "church_bell", 0.7f, autoPlay = false, loop = false),
            ),
            scene(
                "tavern", "Tavern",
                Layer("Tavern music", "tavern_music", 0.55f),
                Layer("Tavern chatter", "tavern_chatter", 0.7f),
                Layer("Hearth fire", "hearth_fire", 0.6f),
                Layer("Rain outside", "rain", 0.35f, autoPlay = false),
            ),
            scene(
                "dungeon", "Dungeon",
                Layer("Dark drone", "dark_drone", 0.6f),
                Layer("Water drips", "water_drips", 0.7f),
                Layer("Torches", "torches", 0.5f),
                Layer("Chains", "chains", 0.5f),
            ),
            scene(
                "market", "Market",
                Layer("Market crowd", "market_crowd", 0.75f),
                Layer("Horse carts", "horse_cart", 0.45f),
                Layer("Street musician", "tavern_music", 0.35f, autoPlay = false),
                Layer("Wind", "wind", 0.3f, autoPlay = false),
            ),
            scene(
                "forest", "Forest",
                Layer("Birdsong", "birdsong", 0.7f),
                Layer("Forest breeze", "forest_breeze", 0.5f),
                Layer("Stream", "stream", 0.45f),
                Layer("Crickets (night)", "crickets", 0.6f, autoPlay = false),
                Layer("Rain", "rain", 0.5f, autoPlay = false),
            ),
            scene(
                "cave", "Cave",
                Layer("Cave wind", "cave_wind", 0.6f),
                Layer("Water drips", "water_drips", 0.7f),
                Layer("Deep drone", "dark_drone", 0.4f),
                Layer("Underground stream", "stream", 0.35f, autoPlay = false),
            ),
        ),
    )

    fun events() = listOf(
        SoundEvent("event-fire", "Fireball", asset("event_fire"), icon = "fire", color = "ember"),
        SoundEvent("event-explosion", "Explosion", asset("event_explosion"), icon = "explosion", color = "crimson"),
        SoundEvent("event-light", "Holy light", asset("event_light"), icon = "light", color = "gold"),
        SoundEvent("event-thunder", "Thunder", asset("event_thunder"), icon = "thunder", color = "azure"),
        SoundEvent("event-sword", "Sword clash", asset("event_sword"), icon = "sword", color = "steel"),
        SoundEvent("event-magic", "Arcane spell", asset("event_magic"), icon = "magic", color = "violet"),
        SoundEvent("event-roar", "Monster roar", asset("event_roar"), icon = "beast", color = "emerald"),
        SoundEvent("event-arrows", "Arrow volley", asset("event_arrows"), icon = "arrow", color = "umber"),
    )

    private class Layer(
        val name: String,
        val sound: String,
        val volume: Float,
        val autoPlay: Boolean = true,
        val loop: Boolean = true,
    )

    private fun scene(key: String, name: String, vararg layers: Layer) = Scene(
        id = "default-$key",
        name = name,
        background = "builtin:$key",
        layers = layers.map {
            SoundLayer(
                id = "default-$key-${it.sound}",
                name = it.name,
                uri = asset(it.sound),
                volume = it.volume,
                autoPlay = it.autoPlay,
                loop = it.loop,
            )
        },
    )
}
